import "./globals.css";
import { LayoutProvider } from "@/context/layout-context";
import { Josefin_Sans, Geist } from "next/font/google";
import { Header } from "@/components/header/Header";
import { cn } from "@/lib/utils/cn";
import { Sidebar } from "@/components/sidebar/Sidebar";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const josefin = Josefin_Sans({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: {
    template: "%s | Medical",
    default: "Medical ",
  },
  description: "Generated by Next.js",
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={`${josefin.className} bg-gray-50 mx-1 `}>
        <LayoutProvider>
          <div className="max-w-7xl mx-auto px-1">
            <Header />
            <div className="flex gap-1 md:gap-6 my-4 relative">
              <Sidebar />
              <main className="max-w-7xl flex-1 min-w-0 flex flex-col gap-6  ">
                {children}
              </main>
            </div>{" "}
          </div>
        </LayoutProvider>
      </body>
    </html>
  );
}
